/**
 * @file session-types.ts
 * Serializable QA session models shared by planning, review, execution, and reporting.
 * Runtime persistence and state helpers live in session.ts.
 */

import type { BranchContext } from "./context-types.js";

/**
 * Represents a single behavior scenario mapped to acceptance criteria.
 */
export type Scenario = {
  /** Unique scenario identifier (e.g. 'S1'). */
  id: string;
  /** Short human-readable title describing the scenario. */
  title: string;
  /** Associated acceptance criteria IDs (e.g. ['AC1']). */
  criteria: string[];
  /** Classification of scenario behavior boundary. */
  kind: "normal" | "boundary" | "error" | "regression";
  /** Ordered list of user or test interaction steps. */
  steps: string[];
  /** Expected outcome after executing the steps. */
  expected: string;
  /** Current approval status of the scenario. */
  status: "pending" | "selected" | "approved" | "excluded";
  /** Rationale if the scenario was modified or excluded. */
  reason: string;
};

/**
 * Specification for a test file generated by the AI model.
 */
export type GeneratedTest = {
  /** Unique test identifier (e.g. 'T1'). */
  id: string;
  /** Target relative file path within the project. */
  path: string;
  /** Kind of test suite. */
  kind: "browser" | "unit" | "integration" | "support";
  /** Designated runner to execute this test file. */
  runner: "playwright" | "vitest" | "jest" | "node";
  /** Scenario IDs validated by this test. */
  scenarioIds: string[];
  /** Stated purpose and goal of the test. */
  purpose: string;
  /** Expected test outcome or behavior. */
  expected: string;
  /** Full source code content of the generated test file. */
  content: string;
  /** Identifiers of auxiliary support files required by this test. */
  supportIds: string[];
  /** SHA-256 hash of the content for tamper detection. */
  sha256: string;
  /** Whether the developer approved this test for execution. */
  approved: boolean;
};

/**
 * Outcome of interactive browser exploration for a given scenario.
 */
export type Exploration = {
  /** Associated scenario identifier. */
  scenarioId: string;
  /** Observation result state. */
  status: "observed" | "failed" | "incomplete";
  /** Sequence of actions taken during exploration. */
  steps: string[];
  /** Notes on what was observed on the page. */
  observed: string;
  /** Paths to captured screenshot and trace artifacts. */
  evidence: string[];
};

/**
 * Record of an executed test runner invocation.
 */
export type ExecutionResult = {
  /** Unique execution record UUID. */
  id: string;
  /** Test revision number executed. */
  revision: number;
  /** Phase of execution (pre-existing baseline vs generated). */
  phase: "existing" | "generated";
  /** Runner name (playwright, vitest, jest, node). */
  runner: string;
  /** List of test identifiers executed. */
  testIds: string[];
  /** Executed files and their content hashes. */
  files: { path: string; sha256: string }[];
  /** High-level execution status. */
  status: "passed" | "failed" | "blocked" | "invalid";
  /** Directory containing logs, traces, and results. */
  artifacts: string;
  /** Explanation or error summary if not passed. */
  reason: string;
  /** ISO timestamp when execution commenced. */
  startedAt: string;
  /** Individual file-level check outcomes if available. */
  checks?: { testId: string; status: ExecutionResult["status"] }[];
};

/**
 * Defect, discrepancy, or environment issue discovered during QA.
 */
export type Finding = {
  /** Unique finding UUID. */
  id: string;
  /** Execution ID that produced this finding. */
  executionId: string;
  /** Related scenario identifiers. */
  scenarioIds: string[];
  /** Category of finding. */
  category: "observed-failure" | "invalid-test" | "environment" | "incomplete";
  /** Description of the observed failure or behavior. */
  observed: string;
  /** Hypothesis regarding the root cause. */
  suspectedCause: string;
  /** Recommendation for addressing the issue. */
  suggestedFix: string;
  /** Source code locations relevant to the finding. */
  source: string[];
  /** File paths to logs, traces, and screenshots. */
  evidence: string[];
};

/**
 * Automatic selection or developer review recorded on a session entity.
 */
export type Feedback = {
  /** Unique feedback UUID. */
  id: string;
  /** Entity target identifier (e.g. test ID, finding ID, or 'plan'). */
  targetId: string;
  /** Revision number when feedback was provided. */
  revision: number;
  /** Action or classification taken (e.g. 'approved', 'rejected'). */
  decision: string;
  /** Justification or instructions provided by developer. */
  reason: string;
  /** ISO timestamp when feedback was recorded. */
  at: string;
};

/**
 * Complete, serializable state of an agent-qa testing session.
 */
export type Session = {
  /** Schema version indicator. */
  version: 2;
  /** Unique session identifier string. */
  id: string;
  /** Directory where session files and artifacts are stored. */
  dir: string;
  /** Creation timestamp. */
  createdAt: string;
  /** Last update timestamp. */
  updatedAt: string;
  /** Current active stage in the QA pipeline. */
  stage:
    | "context"
    | "plan"
    | "explore"
    | "generate"
    | "review-tests"
    | "execute"
    | "findings"
    | "complete";
  /** Overall outcome status of the session. */
  status: "active" | "passed" | "partial" | "failed" | "blocked" | "cancelled";
  /** Initial CLI input options and parameters. */
  input: {
    depth?: "standard" | "deep";
    explicitCriteria?: boolean;
    repo: string;
    url: string;
    intent: string;
    criteria: string[];
    changeType: "feature" | "bug-fix";
    base: string;
    local: boolean;
    context: string[];
    model?: string;
    timeout: number;
    headless: boolean;
  };
  /** Collected Git context and file tree. */
  context?: BranchContext;
  /** Prerequisites, with assumed or developer-confirmed provenance. */
  assumptions: {
    serverMatchesSource: boolean;
    repeatableData: boolean;
    basis?: "assumed" | "developer-confirmed";
  };
  /** High-level summary of proposed test strategy. */
  summary: string;
  /** Discrepancies between intent and commit log. */
  conflicts: string[];
  /** Known gaps or missing coverage items. */
  gaps: string[];
  /** Proposed and reviewed test scenarios. */
  scenarios: Scenario[];
  /** Browser exploration results. */
  explorations: Exploration[];
  /** Versioned revisions of generated test suites. */
  revisions: {
    number: number;
    dir: string;
    tests: GeneratedTest[];
    review: string;
    feedback: string;
  }[];
  /** Records of all test execution runs. */
  executions: ExecutionResult[];
  /** Observed test failures and environment findings. */
  findings: Finding[];
  /** Append-only log of developer review feedback. */
  feedback: Feedback[];
  /** Tests exported into the destination repository. */
  exports: {
    testId: string;
    revision: number;
    destination: string;
    sha256: string;
  }[];
  /** Overall session outcome rationale or failure message. */
  reason: string;
};
