/**
 * @file session.ts
 * Session data structures, state persistence, reporting, and hash validation.
 * Manages atomic writes of session history, execution findings, user feedback,
 * and markdown report generation.
 */

import { createHash, randomUUID } from "node:crypto";
import {
  mkdir,
  readFile,
  rename,
  writeFile,
  realpath,
  lstat,
} from "node:fs/promises";
import { dirname, join, resolve, relative, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";
import type { BranchContext } from "./branch.js";
import { safeRelative } from "./branch.js";
import { record } from "./contracts.js";

/**
 * Root directory of the agent-qa tool package.
 */
export const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/**
 * Computes hexadecimal SHA-256 digest of input string content.
 *
 * @param content - String content to hash.
 * @returns 64-character hexadecimal SHA-256 hash string.
 */
export const sha256 = (content: string): string =>
  createHash("sha256").update(content).digest("hex");

/**
 * Represents a single behavior scenario mapped to acceptance criteria.
 */
export type Scenario = {
  /** Unique scenario identifier (e.g. 'S1'). */
  id: string;
  /** Short human-readable title describing the scenario. */
  title: string;
  /** Associated acceptance criteria IDs (e.g. ['AC1']). */
  criteria: string[];
  /** Classification of scenario behavior boundary. */
  kind: "normal" | "boundary" | "error" | "regression";
  /** Ordered list of user or test interaction steps. */
  steps: string[];
  /** Expected outcome after executing the steps. */
  expected: string;
  /** Current approval status of the scenario. */
  status: "pending" | "approved" | "excluded";
  /** Rationale if the scenario was modified or excluded. */
  reason: string;
};

/**
 * Specification for a test file generated by the AI model.
 */
export type GeneratedTest = {
  /** Unique test identifier (e.g. 'T1'). */
  id: string;
  /** Target relative file path within the project. */
  path: string;
  /** Kind of test suite. */
  kind: "browser" | "unit" | "integration" | "support";
  /** Designated runner to execute this test file. */
  runner: "playwright" | "vitest" | "jest" | "node";
  /** Scenario IDs validated by this test. */
  scenarioIds: string[];
  /** Stated purpose and goal of the test. */
  purpose: string;
  /** Expected test outcome or behavior. */
  expected: string;
  /** Full source code content of the generated test file. */
  content: string;
  /** Identifiers of auxiliary support files required by this test. */
  supportIds: string[];
  /** SHA-256 hash of the content for tamper detection. */
  sha256: string;
  /** Whether the developer approved this test for execution. */
  approved: boolean;
};

/**
 * Outcome of interactive browser exploration for a given scenario.
 */
export type Exploration = {
  /** Associated scenario identifier. */
  scenarioId: string;
  /** Observation result state. */
  status: "observed" | "failed" | "incomplete";
  /** Sequence of actions taken during exploration. */
  steps: string[];
  /** Notes on what was observed on the page. */
  observed: string;
  /** Paths to captured screenshot and trace artifacts. */
  evidence: string[];
};

/**
 * Record of an executed test runner invocation.
 */
export type ExecutionResult = {
  /** Unique execution record UUID. */
  id: string;
  /** Test revision number executed. */
  revision: number;
  /** Phase of execution (pre-existing baseline vs generated). */
  phase: "existing" | "generated";
  /** Runner name (playwright, vitest, jest, node). */
  runner: string;
  /** List of test identifiers executed. */
  testIds: string[];
  /** Executed files and their content hashes. */
  files: { path: string; sha256: string }[];
  /** High-level execution status. */
  status: "passed" | "failed" | "blocked" | "invalid";
  /** Directory containing logs, traces, and results. */
  artifacts: string;
  /** Explanation or error summary if not passed. */
  reason: string;
  /** ISO timestamp when execution commenced. */
  startedAt: string;
  /** Individual file-level check outcomes if available. */
  checks?: { testId: string; status: ExecutionResult["status"] }[];
};

/**
 * Defect, discrepancy, or environment issue discovered during QA.
 */
export type Finding = {
  /** Unique finding UUID. */
  id: string;
  /** Execution ID that produced this finding. */
  executionId: string;
  /** Related scenario identifiers. */
  scenarioIds: string[];
  /** Category of finding. */
  category: "observed-failure" | "invalid-test" | "environment" | "incomplete";
  /** Description of the observed failure or behavior. */
  observed: string;
  /** Hypothesis regarding the root cause. */
  suspectedCause: string;
  /** Recommendation for addressing the issue. */
  suggestedFix: string;
  /** Source code locations relevant to the finding. */
  source: string[];
  /** File paths to logs, traces, and screenshots. */
  evidence: string[];
};

/**
 * Developer review decision or guidance recorded on a session entity.
 */
export type Feedback = {
  /** Unique feedback UUID. */
  id: string;
  /** Entity target identifier (e.g. test ID, finding ID, or 'plan'). */
  targetId: string;
  /** Revision number when feedback was provided. */
  revision: number;
  /** Action or classification taken (e.g. 'approved', 'rejected'). */
  decision: string;
  /** Justification or instructions provided by developer. */
  reason: string;
  /** ISO timestamp when feedback was recorded. */
  at: string;
};

/**
 * Complete, serializable state of an agent-qa testing session.
 */
export type Session = {
  /** Schema version indicator. */
  version: 2;
  /** Unique session identifier string. */
  id: string;
  /** Directory where session files and artifacts are stored. */
  dir: string;
  /** Creation timestamp. */
  createdAt: string;
  /** Last update timestamp. */
  updatedAt: string;
  /** Current active stage in the QA pipeline. */
  stage:
    | "context"
    | "plan"
    | "explore"
    | "generate"
    | "review-tests"
    | "execute"
    | "findings"
    | "complete";
  /** Overall outcome status of the session. */
  status: "active" | "passed" | "failed" | "blocked" | "cancelled";
  /** Initial CLI input options and parameters. */
  input: {
    repo: string;
    url: string;
    intent: string;
    criteria: string[];
    changeType: "feature" | "bug-fix";
    base: string;
    local: boolean;
    context: string[];
    model?: string;
    timeout: number;
    headless: boolean;
  };
  /** Collected Git context and file tree. */
  context?: BranchContext;
  /** Assumptions confirmed by the developer. */
  assumptions: { serverMatchesSource: boolean; repeatableData: boolean };
  /** High-level summary of proposed test strategy. */
  summary: string;
  /** Discrepancies between intent and commit log. */
  conflicts: string[];
  /** Known gaps or missing coverage items. */
  gaps: string[];
  /** Proposed and reviewed test scenarios. */
  scenarios: Scenario[];
  /** Browser exploration results. */
  explorations: Exploration[];
  /** Versioned revisions of generated test suites. */
  revisions: {
    number: number;
    dir: string;
    tests: GeneratedTest[];
    review: string;
    feedback: string;
  }[];
  /** Records of all test execution runs. */
  executions: ExecutionResult[];
  /** Observed test failures and environment findings. */
  findings: Finding[];
  /** Append-only log of developer review feedback. */
  feedback: Feedback[];
  /** Tests exported into the destination repository. */
  exports: {
    testId: string;
    revision: number;
    destination: string;
    sha256: string;
  }[];
  /** Overall session outcome rationale or failure message. */
  reason: string;
};

/**
 * Initializes and persists a new QA session on disk.
 *
 * @param input - Session configuration options.
 * @returns Initialized Session object.
 */
export async function newSession(input: Session["input"]): Promise<Session> {
  const id =
    "session-" +
    new Date().toISOString().replace(/[:.]/g, "-") +
    "-" +
    randomUUID().slice(0, 8);
  const dir = join(root, ".agent-qa", id);
  await mkdir(dir, { recursive: true, mode: 0o700 });
  const session: Session = {
    version: 2,
    id,
    dir,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stage: "context",
    status: "active",
    input,
    assumptions: { serverMatchesSource: false, repeatableData: false },
    summary: "",
    conflicts: [],
    gaps: [],
    scenarios: [],
    explorations: [],
    revisions: [],
    executions: [],
    findings: [],
    feedback: [],
    exports: [],
    reason: "",
  };
  await saveSession(session);
  return session;
}

/**
 * Atomically writes session state and reports (JSON and Markdown) to disk.
 *
 * @param session - Session object to persist.
 */
export async function saveSession(session: Session): Promise<void> {
  session.updatedAt = new Date().toISOString();
  const content = JSON.stringify(session, null, 2) + "\n";
  const temp = join(session.dir, "session-" + randomUUID() + ".tmp");
  await writeFile(temp, content, { mode: 0o600 });
  await rename(temp, join(session.dir, "session.json"));
  await writeFile(join(session.dir, "report.json"), content, { mode: 0o600 });
  await writeFile(join(session.dir, "report.md"), renderReport(session), {
    mode: 0o600,
  });
}

/**
 * Loads and validates an existing session record from disk by session ID.
 *
 * @param id - Session identifier string (e.g. 'session-...').
 * @returns Deserialized and validated Session object.
 * @throws {Error} If ID format is invalid, file missing, or schema validation fails.
 */
export async function loadSession(id: string): Promise<Session> {
  if (!/^session-[\w-]+$/.test(id)) {
    throw new Error("Use the printed session ID, not a path.");
  }
  const dir = await realpath(join(root, ".agent-qa", id));
  const value: unknown = JSON.parse(
    await readFile(join(dir, "session.json"), "utf8"),
  );
  if (
    !record(value) ||
    value.version !== 2 ||
    value.id !== id ||
    !record(value.input) ||
    [
      "scenarios",
      "revisions",
      "executions",
      "feedback",
      "findings",
      "gaps",
      "conflicts",
      "explorations",
      "exports",
    ].some((key) => !Array.isArray(value[key])) ||
    ["repo", "url", "intent", "base"].some(
      (key) =>
        typeof (value.input as Record<string, unknown>)[key] !== "string",
    ) ||
    !Array.isArray(value.input.criteria) ||
    !record(value.assumptions) ||
    typeof value.summary !== "string" ||
    ![
      "context",
      "plan",
      "explore",
      "generate",
      "review-tests",
      "execute",
      "findings",
      "complete",
    ].includes(String(value.stage))
  ) {
    throw new Error("Invalid or unsupported session record.");
  }
  const session = value as unknown as Session;
  session.dir = dir;
  return session;
}

/**
 * Appends developer feedback to the session history.
 *
 * @param session - Target session object.
 * @param targetId - Entity ID or stage being reviewed.
 * @param decision - Decision classification.
 * @param reason - Explanation or instruction notes.
 */
export function feedback(
  session: Session,
  targetId: string,
  decision: string,
  reason: string,
): void {
  session.feedback.push({
    id: randomUUID(),
    targetId,
    revision: session.revisions.length,
    decision,
    reason,
    at: new Date().toISOString(),
  });
}

/**
 * Computes the CLI process exit code based on session status.
 *
 * @param session - Evaluated session object.
 * @returns 0 on pass, 1 on test failure, 2 on blockage or cancellation.
 */
export function sessionExitCode(session: Session): number {
  if (session.status === "failed") {
    return 1;
  }
  if (session.status !== "passed" || session.stage !== "complete") {
    return 2;
  }
  return 0;
}

/**
 * Identifies approved scenarios that have not been fully explored or lack passing tests.
 *
 * @param session - Session to inspect.
 * @returns List of description strings for unresolved coverage gaps.
 */
export function coverageGaps(session: Session): string[] {
  const revision = session.revisions.at(-1);
  return session.scenarios
    .filter((item) => item.status === "approved")
    .flatMap((item) => {
      const observed = session.explorations.find(
        (flow) => flow.scenarioId === item.id && flow.status !== "incomplete",
      );
      const tests =
        revision?.tests.filter(
          (test) =>
            test.approved &&
            test.kind !== "support" &&
            test.scenarioIds.includes(item.id),
        ) ?? [];
      const executed = tests.some((test) =>
        session.executions.some(
          (run) =>
            run.revision === revision?.number &&
            run.phase === "generated" &&
            run.testIds.includes(test.id) &&
            (run.checks?.find((check) => check.testId === test.id)?.status ??
              run.status) === "passed",
        ),
      );
      const needsBrowser =
        !tests.length || tests.some((test) => test.kind === "browser");
      return [
        ...(needsBrowser && !observed
          ? [`${item.id}: exploration incomplete`]
          : []),
        ...(!executed ? [`${item.id}: no passing approved test`] : []),
      ];
    });
}

/**
 * Renders a complete Markdown summary report of the session, including
 * acceptance scope, exploration findings, execution history, and developer feedback.
 *
 * @param session - Session to format into Markdown.
 * @returns Formatted Markdown report string.
 */
export function renderReport(session: Session): string {
  const criteriaText = session.input.criteria
    .map((text, i) => `- AC${i + 1}: ${text}`)
    .join("\n");

  const scenariosText = session.scenarios
    .map(
      (item) =>
        `- ${item.id} [${item.status}] ${item.title} (${item.criteria.join(", ")}, ${item.kind})\n  Expected: ${item.expected}${item.reason ? `; reason: ${item.reason}` : ""}`,
    )
    .join("\n");

  const gapsList = [
    ...session.gaps,
    ...coverageGaps(session),
    ...(session.context?.skipped ?? []),
  ];
  const gapsText =
    gapsList.map((item) => `- ${item}`).join("\n") || "None recorded.";

  const explorationsText =
    session.explorations
      .map(
        (item) =>
          `- ${item.scenarioId} ${item.status}: ${item.observed}; evidence: ${item.evidence.join(", ")}`,
      )
      .join("\n") || "Pending.";

  const executionsText =
    session.executions
      .map(
        (item) =>
          `- ${item.id} revision ${item.revision} ${item.phase} ${item.runner}: ${item.status}. ${item.reason}\n  Evidence: ${item.artifacts}`,
      )
      .join("\n") || "None.";

  const findingsText =
    session.findings
      .map(
        (item) =>
          `- ${item.id} (${item.category}): ${item.observed}\n  Suspected cause: ${item.suspectedCause || "Unknown."}\n  Suggested fix: ${item.suggestedFix || "Inspect retained evidence."}\n  Source: ${item.source.join(", ") || "None cited."}; evidence: ${item.evidence.join(", ")}`,
      )
      .join("\n") || "None recorded.";

  const feedbackText =
    session.feedback
      .map(
        (item) =>
          `- ${item.at} ${item.targetId} revision ${item.revision}: ${item.decision}; ${item.reason}`,
      )
      .join("\n") || "None.";

  const exportsText =
    session.exports
      .map(
        (item) =>
          `- ${item.testId} revision ${item.revision}: ${item.destination} (${item.sha256})`,
      )
      .join("\n") || "None.";

  return (
    `# QA session ${session.id}\n\n` +
    `Status: **${session.status}**. Stage: ${session.stage}. ${session.reason}\n\n` +
    `${session.summary}\n\n` +
    `## Source and assumptions\n\n` +
    `Repository: ${session.input.repo}\n\n` +
    `Base: ${session.context?.base ?? session.input.base}; head: ${session.context?.head ?? "pending"}; merge base: ${session.context?.mergeBase ?? "pending"}; local edits: ${session.input.local}.\n\n` +
    `Server source revision developer-confirmed: ${session.assumptions.serverMatchesSource}. Backend reset/repeatable data developer-confirmed: ${session.assumptions.repeatableData}. Browser isolation does not reset backend state or isolate the OS. Generated tests run as trusted reviewed local code.\n\n` +
    `## Acceptance scope\n\n` +
    `${criteriaText}\n\n` +
    `${scenariosText}\n\n` +
    `## Coverage gaps and omitted context\n\n` +
    `${gapsText}\n\n` +
    `## Exploration\n\n` +
    `${explorationsText}\n\n` +
    `## Executions\n\n` +
    `${executionsText}\n\n` +
    `## Findings\n\n` +
    `${findingsText}\n\n` +
    `## Developer feedback (append only)\n\n` +
    `${feedbackText}\n\n` +
    `## Accepted exports\n\n` +
    `${exportsText}\n`
  );
}

/**
 * Validates that a target file path resolves within the specified directory
 * without escaping through parent traversal or symlink hops.
 *
 * @param dir - Containing directory path.
 * @param path - Relative path to resolve.
 * @returns Canonical absolute destination path.
 * @throws {Error} If destination escapes dir through directory traversal or symlinks.
 */
export async function containedPath(
  dir: string,
  path: string,
): Promise<string> {
  const destination = join(dir, safeRelative(path));
  const rootDir = await realpath(dir);
  let parent = dirname(destination);
  while (true) {
    const stat = await lstat(parent).catch(() => undefined);
    if (stat) {
      const canonical = await realpath(parent);
      const rel = relative(rootDir, canonical);
      if (rel === ".." || rel.startsWith("../") || isAbsolute(rel)) {
        throw new Error("Destination escapes repository through a symlink.");
      }
      break;
    }
    parent = dirname(parent);
  }
  return destination;
}

